/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    LanguageSwitch: typeof import('./components/LanguageSwitch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpeakingRecorder: typeof import('./components/SpeakingRecorder.vue')['default']
    VideoPlayer: typeof import('./components/VideoPlayer.vue')['default']
    VocabularyCard: typeof import('./components/VocabularyCard.vue')['default']
  }
}
